/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      collapsible: false,
      collapsed: false,
      items: [
        'engineeringnexus/about',
        'engineeringnexus/knowledge-map',
        'engineeringnexus/content-system',
      ],
    },
    'engineeringnexus/platform-engineering',
    {
      type: 'category',
      label: 'DevOps',
      collapsible: true,
      collapsed: true,
      items: ['devops/overview'],
    },
    {
      type: 'category',
      label: 'Infrastructure as a Service',
      collapsible: true,
      collapsed: true,
      items: [
        'iaas/overview',
        'engineeringnexus/projects/private-compute-cluster',
        'OpenStack/Private Compute Cluster/summary',
        'OpenStack/Private Compute Cluster/Architecture Overview/NeutronNetworkArchcitecture',
      ],
    },
    {
      type: 'category',
      label: 'CAT',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Quants',
          collapsible: true,
          collapsed: true,
          items: [
            'cat/quants/overview',
            'cat/quants/universal-speed-rules',
            {
              type: 'category',
              label: 'Arithmetic',
              collapsible: true,
              collapsed: true,
              items: [
                'cat/quants/arithmetic/percentages',
                'cat/quants/arithmetic/profit-loss-and-discount',
                'cat/quants/arithmetic/averages',
                'cat/quants/arithmetic/ratio-and-proportion',
                'cat/quants/arithmetic/mixtures-and-alligation',
                'cat/quants/arithmetic/time-speed-and-distance',
                'cat/quants/arithmetic/time-and-work',
                'cat/quants/arithmetic/simple-and-compound-interest',
              ],
            },
            {
              type: 'category',
              label: 'Algebra',
              collapsible: true,
              collapsed: true,
              items: [
                'cat/quants/algebra/linear-equations',
                'cat/quants/algebra/quadratic-equations',
                'cat/quants/algebra/inequalities',
                'cat/quants/algebra/functions',
                'cat/quants/algebra/logarithms',
                'cat/quants/algebra/sequences-and-series',
              ],
            },
            {
              type: 'category',
              label: 'Geometry and Mensuration',
              collapsible: true,
              collapsed: true,
              items: [
                'cat/quants/geometry-mensuration/lines-and-angles',
                'cat/quants/geometry-mensuration/triangles',
                'cat/quants/geometry-mensuration/circles',
                'cat/quants/geometry-mensuration/quadrilaterals-and-polygons',
                'cat/quants/geometry-mensuration/2d-mensuration',
                'cat/quants/geometry-mensuration/3d-mensuration',
                'cat/quants/geometry-mensuration/coordinate-geometry',
              ],
            },
            {
              type: 'category',
              label: 'Number System',
              collapsible: true,
              collapsed: true,
              items: [
                'cat/quants/number-system/hcf-and-lcm',
                'cat/quants/number-system/divisibility',
                'cat/quants/number-system/remainders',
                'cat/quants/number-system/factors',
                'cat/quants/number-system/factorials',
                'cat/quants/number-system/surds-and-indices',
                'cat/quants/number-system/base-system',
              ],
            },
            {
              type: 'category',
              label: 'Modern Maths',
              collapsible: true,
              collapsed: true,
              items: [
                'cat/quants/modern-maths/permutation-and-combination',
                'cat/quants/modern-maths/probability',
                'cat/quants/modern-maths/set-theory',
                'cat/quants/modern-maths/venn-diagrams',
                'cat/quants/modern-maths/binomial-theorem',
              ],
            },
            'cat/quants/cat-accuracy-checklist',
            'cat/quants/fast-practice-order',
          ],
        },
        'cat/varc',
        'cat/dilr',
      ],
    },
    {
      type: 'category',
      label: 'Competitive Coding',
      collapsible: true,
      collapsed: true,
      items: [
        'engineeringnexus/problem-solving',
        'competitive-coding/leetcode',
        'competitive-coding/katas',
        'competitive-coding/codeforces',
      ],
    },
    {
      type: 'category',
      label: 'SDR Radio',
      collapsible: true,
      collapsed: true,
      items: ['sdr-radio/overview'],
    },
    {
      type: 'category',
      label: 'Hangar',
      collapsible: true,
      collapsed: true,
      items: ['hangar/overview'],
    },
    {
      type: 'category',
      label: 'MCP',
      collapsible: true,
      collapsed: true,
      items: ['mcp/overview'],
    },
    {
      type: 'category',
      label: 'Custom AI Models',
      collapsible: true,
      collapsed: true,
      items: ['custom-ai-models/overview'],
    },
    {
      type: 'category',
      label: 'Games',
      collapsible: true,
      collapsed: true,
      items: ['games/overview'],
    },
    {
      type: 'category',
      label: 'Exploratory Projects',
      collapsible: true,
      collapsed: true,
      items: ['exploratory-projects/overview'],
    },
    {
      type: 'category',
      label: 'More Engineering',
      collapsible: true,
      collapsed: true,
      items: [
        'engineeringnexus/ai-architecture',
        'engineeringnexus/hardware-edge',
        'engineeringnexus/build-logs',
      ],
    },
    {
      type: 'category',
      label: 'Visual Systems',
      collapsible: true,
      collapsed: true,
      items: ['engineeringnexus/visual-lab'],
    },
  ],
};

module.exports = sidebars;
